# Generated by Django 3.2.8 on 2021-10-27 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('imagen', models.FileField(upload_to='imagenes/')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laguindaapi.oferta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=0, max_digits=5)),
                ('comentario', models.CharField(max_length=500)),
                ('valoproduc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laguindaapi.producto')),
                ('valousu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laguindaapi.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compoingre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laguindaapi.ingrediente')),
                ('compoprodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laguindaapi.producto')),
            ],
        ),
    ]
