# Generated by Django 3.0.7 on 2021-10-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laguindaapi', '0003_auto_20211013_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(upload_to='imagenes/'),
        ),
    ]
