# Generated by Django 3.0.7 on 2021-10-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laguindaapi', '0004_auto_20211015_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='orden',
        ),
    ]
