# Generated by Django 3.2.8 on 2021-10-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laguindaapi', '0005_remove_componente_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='compoingre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laguindaapi.ingrediente'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='compoprodu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laguindaapi.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laguindaapi.oferta'),
        ),
        migrations.AlterField(
            model_name='valoracione',
            name='valoproduc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laguindaapi.producto'),
        ),
        migrations.AlterField(
            model_name='valoracione',
            name='valousu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laguindaapi.usuario'),
        ),
    ]
